Update gradle.yml

diff --git a/.github/workflows/gradle.yml b/.github/workflows/gradle.yml
--- a/.github/workflows/gradle.yml
+++ b/.github/workflows/gradle.yml
@@ -26,7 +26,13 @@ jobs:
 
     # Gradle Build를 위한 권한 부여
     - name: Grant execute permission for gradlew
-      run: chmod +x gradlew
+      run: |
+        if [ -f gradlew ]; then
+          chmod +x gradlew
+        else
+          echo "gradlew file not found!"
+          exit 1
+        fi
 
     # Gradle Build (test 제외)
     - name: Build with Gradle
